[[redirects]]
  from = "https://peoplewhoafrica.notion.site/peoplewhoafrica/PeopleWho-4d3ba5946fb34199bde43408cd052aae"
  to = "https://peoplewhoafrica.tk"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/talent"
  to = "https://peoplewhoafrica.notion.site/bc1d0d555f784e28a3b944a8114d8970?v=1fcb6a6cb60b422d905ff13ef2e15a6a"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/jobs"
  to = "https://peoplewhoafrica.notion.site/7470fe0f2e934ad0a8b291f4e2bccf76?v=2ba2523829124acea7792fcee1b3f795"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/runningcosts"
  to = "https://peoplewhoafrica.notion.site/694397ac905f45eaa06b44affb3e6388?v=56812a27b1fa44a2a93fc7f4aaf3446b"
  status = 302
  force = true # COMMENT: ensure that we always redirect
  
  [[redirects]]
  from = "/support"
  to = "https://peoplewhoafrica.notion.site/Supporters-bb4112eb61bc4e97a0b235db6185e6da"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/designresources"
  to = "https://peoplewhoafrica.notion.site/Design-Resources-NEW-0040bdc03bbe445cb494bfed2629d4df"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/testimonials"
  to = "https://peoplewhoafrica.notion.site/Testimonials-f29338c04d9f44b1b9ae1fd211776cb8"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/thestory"
  to = "https://peoplewhoafrica.notion.site/The-story-behind-PeopleWho-a110ac3035c34109988aeb5885f1f344"
  status = 302
  force = true # COMMENT: ensure that we always redirect